# Generated by Django 3.1.7 on 2021-03-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
