# Generated by Django 3.1.7 on 2021-03-27 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210327_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unid_number',
            new_name='unit_name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='curso_id',
        ),
        migrations.AddField(
            model_name='week',
            name='curso_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
    ]
