# Generated by Django 3.1.7 on 2021-03-27 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210327_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='curso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
    ]
