# Generated by Django 3.1.7 on 2021-03-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210327_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
