# Generated by Django 3.1.7 on 2021-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nombreCompleto',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
